### ISSUE TITLE
Parametrize IRI dereference endpoint

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#105]
Parametrize IRI dereference endpoint at least for Dataset IRI (so that it can run in various environments, e.g. https://dev.nkod.opendata.cz/describe/?uri=https://data.gov.cz/zdroj/datové-sady/https---opendata.plzen.eu-api-3-action-package_show-id-gis-rastrovy-podklad-uzemni-plan-plzen-1-zakladni-vykres

**Comment by skodapetr** [comment]
How parametrize? Dataset IRI is used as a dereference IRI. 

So you mean to add some sort of a prefix?

**Comment by jakubklimek** [comment]
Yes, as written in the issue. I.e. ```https://dev.nkod.opendata.cz/describe/?uri=``` would be the prefix.
