### ISSUE TITLE
Fix accessibility issues

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#108]
Chrome 70 audits reveal some accessibility issues to be fixed.

**Comment by skodapetr** [comment]
There are some issues 

_Form elements do not have associated labels_
```
<input autocomplete="off" type="text" aria-autocomplete="both" aria-expanded="false" aria-haspopup="listbox" role="combobox" class="rbt-input-main form-control rbt-input" value="">
```
This is an external component.

_Background and foreground colors do not have a sufficient contrast ratio._
For exceptional publisher icon. So we need a different colour @jakubklimek.

Another instance of this error is for tag clouds, should we want to address it we would need to probably implement custom colour generator.
