### ISSUE TITLE
Consider use of CDN

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/dcat-ap-viewer#110]
* https://cdnjs.cloudflare.com/ajax/libs/react/16.4.2/cjs/react.production.min.js
* https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.4.2/cjs/react-dom.production.min.js
* https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js
and others ..

**Comment by akuckartz** [comment]
Why?

**Comment by skodapetr** [comment]
It would decrease the size of the bundle (yep, it's not that important at the end). Of course, the benefit strongly depends on the overall usage of CDNs nowadays, especially by React application.

It would not bring a dependency on being online as even now we are using CDN for Bootstrap.

However, it's for consideration so any ideas/arguments are welcomed here.

**Comment by skodapetr** [comment]
At the end, we decide not to do this, but rather focus on minimization of the bundle size in #112.
