### ISSUE TITLE
Change behavior for custom licenses

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#113]
![image](https://user-images.githubusercontent.com/718827/47854433-01f54a00-dde2-11e8-89fb-268adb0a96ae.png)
Now it is unclear to what the Custom license relates. Therefore, I propose to change it to be consistent with:
![image](https://user-images.githubusercontent.com/718827/47854501-2bae7100-dde2-11e8-9378-76d27d7cbd18.png)
Where the text will be "Vlastní licence"/"Custom license" and the link will be from this text (not visible).

**Comment by skodapetr** [comment]
Ok, so instead of:

Vlastní licence
[https://data.cssz.cz/podminky-uziti](https://data.cssz.cz/podminky-uziti)

we will have?

**Comment by jakubklimek** [comment]
[Vlastní licence](https://data.cssz.cz/podminky-uziti)
Autorské dílo

**Comment by skodapetr** [comment]
Do we have a link to the data?

**Comment by jakubklimek** [comment]
Every dataset of CSSZ, e.g. https://dev.nkod.opendata.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2Fhttps---data.cssz.cz-api-3-action-package_show-id-doba-rizeni-o-namitkach
