### ISSUE TITLE
Terms of use are interpreted wrong

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#116]
These terms of use are correct. However, they are displayed
1) as custom, which is wrong
2) personal data statement is missing - (it is in the data)

https://nkod.nakit.opendata.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2FPoskytovatel2%2F6756646

![image](https://user-images.githubusercontent.com/718827/48140441-138a9600-e2a9-11e8-875f-404554e823ad.png)

**Comment by skodapetr** [comment]
When I access the URL I got ```Nepodařilo se načíst data.``` without the input data it's not possible to fix the issue.

**Comment by jakubklimek** [comment]
I think I resolved the source of this in dcat-ap-forms. Nevertheless, it happens when there is a link to our "specification", but it does not contain the expected IRIs (i.e. for personal data) and maybe we should handle it better here as well.

**Comment by skodapetr** [comment]
The URLs in DAV ends with "/" so that have probably changed somewhere, we need to decide if we want to use with or without the ending "/".
