### ISSUE TITLE
License could open to popup and thus not navigating out of the dataset

### ISSUE THREAD

**Issue by SmallhillCZ** [linkedpipes/dcat-ap-viewer#118]

**Comment by skodapetr** [comment]
There are some questions that need to be clarified here.  As the user can provide a custom link to the license we would need to open popup with iframe - or as a dialogue? Also, keep in mind that the content of the page can be anything (not only text) and may unexpected visual.

**Comment by jakubklimek** [comment]
This was probably observed in the current production version at https://data.gov.cz. It has been since fixed in development version at https://dev.nkod.opendata.cz
