### ISSUE TITLE
Unexpected unexpected value

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#122]
See [this dataset](https://dev.nkod.opendata.cz/datová-sada?iri=https://data.gov.cz/zdroj/datové-sady/CObchodniI/99266) and see the browser console. It contains the following error, which is unexpected, as this value is actually expected:

![image](https://user-images.githubusercontent.com/718827/48349073-743c1900-e683-11e8-831b-23c75218b3ac.png)

**Comment by skodapetr** [comment]
Should be fixed in eb8af911018e071d4742704bb4d3046e30b45b26
