### ISSUE TITLE
Add "LKOD list" to "more"

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#124]
Add a list of LKODs (name (not clickable), publisher (clickable), type (not clickable)) with trash can leading to DAF delete catalog.

**Comment by skodapetr** [comment]
For this we need to put all the LKOD's somewhere. Probably some static file in CoachDB. 
The requires modification of the pipeline.

**Comment by jakubklimek** [comment]
Added to couchdb in dev.nkod...
