### ISSUE TITLE
Special characters escaped in dataset title

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#127]
Dataset title `P' dataset` is displayed correctly in dataset detail, however, in dataset list the character is HTML entity escaped like this:

![image](https://user-images.githubusercontent.com/718827/48778631-0f616e00-ecd6-11e8-931d-09bdeb616cf2.png)

https://nkod.nakit.opendata.cz/datová-sada?iri=https://data.gov.cz/zdroj/datové-sady/Poskytovatel2/6777747

**Comment by jakubklimek** [comment]
This was related to Mustache HTML escaping. `{{{}}}` solved it.

**Comment by jakubklimek** [comment]
Either way, the inconsistency means there is a bug somewhere in viewer?

**Comment by skodapetr** [comment]
Na tohle je třeba tam dát zase ta nevalidní data a podívat se na odpovědi od databází.
