### ISSUE TITLE
Enhance page descriptions in Google search results

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#130]
In google search results, some pages have inappropriate titles, which can be seen in google search console. Examples are:
- "filter by keyword" - title is simply "Datasets"
- "filter by publisher" - title is the publishers name
- ...

**Comment by skodapetr** [comment]
What is the actual title in google search and what is the expected title?

**Comment by jakubklimek** [comment]
We need to decide whether filtered pages should be indexed at all. If yes, we need to represent the current filter in the page title. Currently, there is many results in Google for various filter settings, with all pages having the same "datasets" title.

**Comment by jakubklimek** [comment]
It would be better if the "filtered" pages would not be indexed at all. I am not sure that the current approach with `canonical` [works](https://www.google.com/search?q=site:data.gov.cz+datové+sady&oq=site:data.gov.cz+datové+sady).

**Comment by skodapetr** [comment]
They are only a recommendation, google can decide to ignore them. They are also not used in a same way by Google and other search engines.

I've also heard an opinion that we should actually support indexing of different categories }filters] and use canonicals only for sorting.

But from @jakubklimek it is not clear what action should be taken. Should we use 
```<meta name="robots" content="noindex">``` for dataset list?

**Comment by jakubklimek** [comment]
We agreed that we will add the following to page title:
- Publisher name, when only one is selected
- Theme, when only one is selected
- Keyword, when only one is selected

Also, `canonical` links need to be adjusted (filters added)
