### ISSUE TITLE
Ordering of search results wrong in Czech (NK-9)

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#136]
The ordering does not respect natural Czech ordering. Example:
```
Doprava - NAKIT
Dřeviny - TEST NAKIT Datová sada
Jarča NAKIT
Modrá datová sada NAKIT
P' dataset
Červená datová sada NAKIT
```

We need to investigate how to add Czech locale to Solr and how it affects the English search results

**Comment by skodapetr** [comment]
https://stackoverflow.com/questions/25529355/solr-sorting-with-special-characters

**Comment by skodapetr** [comment]
This is a Solr issue, so we need to know which version of Solr as the versions are not always compatible from the configuration perspective.

**Comment by jakubklimek** [comment]
7.6

**Comment by skodapetr** [comment]
Some additional links for Solr:
* https://blog.griddynamics.com/implementing-autocomplete-with-solr/
* https://blog.griddynamics.com/utilizing-solr-suggester-for-typeahead-search-engines/
* https://opensourceconnections.com/blog/2017/02/20/solr-utf8/

Documentation:
* https://lucene.apache.org/solr/guide/7_6/the-standard-query-parser.html
* https://lucene.apache.org/solr/guide/7_6/suggester.html
* http://lucene.apache.org/solr/guide/7_6/tokenizers.html
* https://lucene.apache.org/solr/guide/7_6/understanding-analyzers-tokenizers-and-filters.html
* http://lucene.apache.org/solr/guide/7_6/field-types-included-with-solr.html
* http://lucene.apache.org/solr/guide/7_6/language-analysis.html
