### ISSUE TITLE
Delete/edit dataset/catalog buttons should also have textual labels for screen readers

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#142]
Delete/edit dataset/catalog buttons should also have textual labels for screen readers and tooltips. This also applies to the "Follow link" buttons.

**Comment by skodapetr** [comment]
How should the title look like for follow up links?
As the title is most of the times reserved for the links pointing towards dataset list, it made no sense to have two links with same "text".

**Comment by jakubklimek** [comment]
"Dereference link"/"Přejít na odkaz"

**Comment by jakubklimek** [comment]
`Smaž datavoou sadu`...

**Comment by jakubklimek** [comment]
`Smaž datavou sadu`...
