### ISSUE TITLE
Autocomplete not working correctly

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#152]
When typing `registr práv a povinností` in the dataset search box, no dataset is suggested. Nevertheless, when I hit enter, matching datasets are found. These should be suggested, otherwise, it seems that they are not there.

**Comment by jakubklimek** [comment]
It works better, but still not with "základní výkres" ("základní výk" shows nothing). Interesting that it works differently at data.gov.cz and nkod-test.opendata.cz (both solr 8.0.0).

**Comment by skodapetr** [comment]
Well if same version of solar is used, then it's ops problem.

**Comment by jakubklimek** [comment]
> Well if same version of solar is used, then it's ops problem.

The current DAV was not redeployed there. It is now.

Nevertheless, there is still an autocomplete issue.

Trying to find `základní výk`, the autocomplete is empty even though the Solr query returns results.

**Comment by skodapetr** [comment]
The used Highlighter component does not support matching in this case.
It use ```<mark className="rbt-highlight-text">Základní vý</mark>``` to highlight.

We can either implement custom highlight or disable it.
