### ISSUE TITLE
Stop supporting IE11

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#155]
There is some code for support of IE11. Since the servers are moving to TLSv1.3, which is not supported by IE11 on Win7 anyway, and on Win10 there are alternatives (Edge), we can stop supporting IE11 altogether.

**Comment by skodapetr** [comment]
The develop targets  "chrome": 41, dropping support for IE 11 in 7ec12be02b659735e422efaead8254bb0716c39d
