### ISSUE TITLE
LKOD: Allow admin to hide "publishers"

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#157]
Typically, there is only one publisher in an LKOD. Therefore, "Publishers" tab and filter should be hidable in configuration.

There may also be publishers interested in having sub-publishers (like Praha). Therefore, this should be hidable, not removed.

**Comment by jakubklimek** [comment]
Now the publishers tab hides, but not the filter

**Comment by jakubklimek** [comment]
This should also make the "publisher" links in dataset list and dataset detail not clickable (as the filter will be disabled)

**Comment by skodapetr** [comment]
Instead of this *custom* options admin should utilize profiles to define desired behaviour.

**Comment by jakubklimek** [comment]
OK, will be resolved in #213
