### ISSUE TITLE
Empty contact point

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/dcat-ap-viewer#164]
For example here: 
https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2Fhttp---opendata.praha.eu-api-3-action-package_show-id-granty-mhmp-usneseni

The reason is empty vcard2006:fn and vcard2006:hasEmail .
What should be visible in that case?

**Comment by jakubklimek** [comment]
For educative reasons, I would leave it as it is. This is caused by empty string values (not missing values) in the input data. Validating this would add complexity to DAV because of invalid input data which I would not like to do.
