### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#174]
Dark mode needs to be added to be consistent with the rest of the data.gov.cz web.
This can be done via modifying CSS accordingly, if there is no direct support in bootstrap.

**Comment by skodapetr** [comment]
@jakubklimek We need to specify colours for all the missing elements. The change also broke the default style.

**Comment by jakubklimek** [comment]
Fixed in d0ab37de2d72d6df9b162ada8a8b21b74a177d65
