### ISSUE TITLE
Missing separator under distribution section title

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#175]
![image](https://user-images.githubusercontent.com/718827/77165120-fcb99d80-6ab1-11ea-9706-19ce69a1e43d.png)
compared to prodcution:
![image](https://user-images.githubusercontent.com/718827/77165159-0b07b980-6ab2-11ea-82db-87b8dd0df012.png)

**Comment by skodapetr** [comment]
This was caused by update of the bootstrap library. The current version does not, by default, put borderline there.
