### ISSUE TITLE
Schema.org Dataset JSON-LD support

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#19]
Include microdata according to https://developers.google.com/search/docs/data-types/datasets

**Comment by skodapetr** [comment]
The first version of json-ld data was added in 7b5a604549b49af26ec5cb7ecda0d2d5afd186b7.

**Comment by jakubklimek** [comment]
Link to catalog points to a catalog record instead of catalog.

**Comment by jakubklimek** [comment]
We need to revisit [the spec](https://developers.google.com/search/docs/data-types/dataset#download) and add more markup - for instance, links for download are missing.

**Comment by skodapetr** [comment]
"closed this on 10 Aug 2017"
Why do you reopen 2 years old issue which is an enhancement, not even a bug?
 The issue is not storytelling or a zombie to raise from the dead.

**Comment by akuckartz** [comment]
BTW: microdata is no longer relevant.

**Comment by skodapetr** [comment]
@jakubklimek Please specify which microdata would you like to be included.

**Comment by jakubklimek** [comment]
@skodapetr not microdata. JSON-LD. And as said above, at least the download URL and data format like in the spec. i.e.
```json
"distribution":[
         {
            "@type":"DataDownload",
            "encodingFormat":"CSV",
            "contentUrl":"http://www.ncdc.noaa.gov/stormevents/ftp.jsp"
         },
         {
            "@type":"DataDownload",
            "encodingFormat":"XML",
            "contentUrl":"http://gis.ncdc.noaa.gov/all-records/catalog/search/resource/details.page?id=gov.noaa.ncdc:C00510"
         }
      ],
```

**Comment by jakubklimek** [comment]
Does not work as intended. In [this dataset](https://dev.nkod.opendata.cz/datová-sada?iri=https://data.gov.cz/zdroj/datové-sady/https---data.cssz.cz-api-3-action-package_show-id-kontroly-plneni-povinnosti-zamestnavatelu-v-oblasti-socialniho-zabezpeceni), it is
1) missing contentUrl
2) format should be the format label, not the format IRI
```json
{
  "@context": "http://schema.org/",
  "@type": "Dataset",
  "name": "Kontroly plnění povinností zaměstnavatelů v oblasti sociálního zabezpečení",
  "description": "Statistika kontrol plnění povinností zaměstnavatelů v oblasti sociálního zabezpečení od roku 2009",
  "url": "https://data.gov.cz/zdroj/datové-sady/https---data.cssz.cz-api-3-action-package_show-id-kontroly-plneni-povinnosti-zamestnavatelu-v-oblasti-socialniho-zabezpeceni",
  "temporalCoverage": "2009-01-01/2019-12-31\"\n",
  "keywords": [
    "kontrola",
    "sociální zabezpečení",
    "statistika",
    "zaměstnavatelé"
  ],
  "creator": {
    "@type": "Organization",
    "name": "Česká správa sociálního zabezpečení"
  },
  "distribution": [
    {
      "@type": "DataDownload",
      "encodingFormat": "http://publications.europa.eu/resource/authority/file-type/CSV"
    },
    {
      "@type": "DataDownload",
      "encodingFormat": "http://publications.europa.eu/resource/authority/file-type/RDF_TRIG"
    }
  ]
}
```

**Comment by jakubklimek** [comment]
format should be the format label, not the format IRI
