### ISSUE TITLE
Autocomplete not working as expected

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#194]
There is a dataset called `Moje druhá DCAT2 datová sada - se službama` in [dev](https://dev.nkod.opendata.cz/datové-sady). However, autocomplete shows nothing for `služ` and other substrings.

**Comment by skodapetr** [comment]
What are the "other substrings" ?

**Comment by jakubklimek** [comment]
When you continue in typing the whole word `službama`
