### ISSUE TITLE
Allow dataset to have datasets in addition to distributions

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/dcat-ap-viewer#198]
URL of examples 
https://dev.nkod.opendata.cz/datov%C3%A9-sady?poskytovatel=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fovm%2FPoskytovatel1
dcterms:hasPart predicate is used to point from parent to children 

We also need to indicate that a dataset is child of another dataset.

**Comment by jakubklimek** [comment]
Additional example: https://dev.nkod.opendata.cz/datová-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2FPoskytovatel2%2F9999994%2F8bdfdaa2744b83e07de94284d057b126
