### ISSUE TITLE
Temporal resolution labels

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#199]
Where do the labels of temporal resolution entities come from? i.e. "měsíce" in:

![image](https://user-images.githubusercontent.com/718827/88543212-f0bd8980-d017-11ea-8b5f-f52e937880a4.png)

**Comment by skodapetr** [comment]
They come from https://github.com/linkedpipes/dcat-ap-viewer/blob/f722e0d660d1cfbe90737f43e8b773b40c16be49/profile/nkod/dataset-detail/properties.jsx#L221
