### ISSUE TITLE
Add link to upper dataset in a hierarchy

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#207]
It could look something like this:
![image](https://user-images.githubusercontent.com/718827/89029126-02f83a00-d32e-11ea-9ce0-733ec0ddbec1.png)

**Comment by skodapetr** [comment]
@jakubklimek  We need to add dataset labels to the labels database. Alternatively we can aad title of parent dataset to each dataset that has a parent.
