### ISSUE TITLE
Resolve issue with labels

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/dcat-ap-viewer#216]
There are now few issues connected to labels mainly related to the fact that Virtuoso does not return language tags.
This one is not a huge problem if we ask only for one specific language.  However, when we ask for multiple languages.
A good example are labels for Themes (in multiple languages) or Formats (where there is no cs language).

How should this issue be adressed. It seems like a solution would be to hardcode selection on cs or en (or reverse order fo en users) labels. And then case them to desired language. This would impact performance and may result in situation where en label is returned as cs label .. 

Can you come up with a better solution?

**Comment by jakubklimek** [comment]
This is [reported to VOS](https://github.com/openlink/virtuoso-opensource/issues/925). Given that this feature is not critical right now, I do not think we need to implement virtuoso-specific workarounds at the moment.
