### ISSUE TITLE
Display "data service name" in the data service properties, if present

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#222]
[Example](https://dev.nkod.opendata.cz/datová-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2FMinFinCZ%2F9999996%2F579129b0750a760e48c7a1f5f915cdc5).
I would add it as another item into the data service properties list.
![image](https://user-images.githubusercontent.com/718827/96838060-a2b5f780-1447-11eb-9ab5-e57337ae80b4.png)

**Comment by skodapetr** [comment]
So we need to read http://purl.org/dc/terms/title from the http://www.w3.org/ns/dcat#DataService and show it in a similar way as "Typ média" ~ value + title. The only issue can be lenght of the string here.

An alternative may be to add it into the DataService title, where is now Distribution title + format type.

**Comment by jakubklimek** [comment]
It seems reasonable to display it in the same place as Distribution title, and only when that one is not present.

**Comment by skodapetr** [comment]
@jakubklimek Do we have test data?
