### ISSUE TITLE
Fix display of local catalogs

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#223]
https://dev.nkod.opendata.cz/lokální-katalogy

**Comment by skodapetr** [comment]
Can you elaborate wthat is the issue? I can see three catalogs there .. so some are missing?

**Comment by jakubklimek** [comment]
Yes, some are missing. E.g. for this dataset: https://dev.nkod.opendata.cz/datová-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2FMinFinCZ%2F9999996%2Fc1ddd16f59c6246b8aafc124c3b58166 (see its RDF representation to see the local catalog).

**Comment by skodapetr** [comment]
Branch ```feature/refactoring)```.
