### ISSUE TITLE
Add support for dcterms:conformsTo URL in DataService

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#224]
Add support for dcterms:conformsTo URL in DataService. Labels should be "Specifikace"/"Specification", as with dcterms:conformsTo in Dataset.

**Comment by skodapetr** [comment]
@jakubklimek Do we have test data? And what predicate should be used?

**Comment by jakubklimek** [comment]
@skodapetr e.g. https://dev.nkod.opendata.cz/datová-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2FMinVnitrCZ%2F1999996%2F9c73b802263c5e0ccf5542f10fbc35bb - and all other codelists from MV ČR. The predicate is dcterms:conformsTo

**Comment by skodapetr** [comment]
1) This should not be added to distribution, only data service.
2) Do we have quality for this ?

**Comment by skodapetr** [comment]
In ```feature/refactoring```  branch.

**Comment by jakubklimek** [comment]
There is something wrong with the tooltip:
![image](https://user-images.githubusercontent.com/718827/99949363-34808f80-2d7b-11eb-9399-3625ba488de6.png)
