### ISSUE TITLE
Missing link to containing dataset in dataset detail

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#230]
The link to containing dataset in [this dataset](http://localhost:8030/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2FMinFinCZ%2F9999996%2F3eb35d2212151cdd7effd3d0f8086ec0) is to `http://localhost:8030/dataset` instead of to the containing dataset detail.

![image](https://user-images.githubusercontent.com/718827/100418461-166ca500-3083-11eb-800d-3cb24577a496.png)

**Comment by skodapetr** [comment]
@jakubklimek They are all localhost ... but I gues you want to say that the link for the parent dataset, in this case ```Datová sada IS CEDR III``` does not point to the dataset detail. It that it?

**Comment by jakubklimek** [comment]
yes
