### ISSUE TITLE
"Loading data" message stuck

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#244]
The loading data message is stuck where distributions or parts of dataset series are supposed to be. This dataset, however, has neither. This is not expected, however, DAV should not crash on it anyway.

https://pod-test.mvcr.gov.cz/datová-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2F00006947%2F833106130%2Fc4ad2c2eb48baea04b67600e907b45aa

**Comment by skodapetr** [comment]
The problem is in the data, where two dataset are returned. But we can ignore the other one ...
