### ISSUE TITLE
404 download errors in Console

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#245]
https://pod-test.mvcr.gov.cz/datová-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2Fhttps---dataor.justice.cz-api-3-action-package_show-id-as-actual-brno-2005

Is there a reason for the 404 errors in the console?

![image](https://user-images.githubusercontent.com/718827/107150549-999d5780-695e-11eb-9add-524ccd4f507d.png)

**Comment by skodapetr** [comment]
Well I think that the red ones are produced by the browser, the error messages by the viewer.  I might add some detail to the message. But the real solution is to get all the labels.
