### ISSUE TITLE
Distribution license shows as unspecified when specified

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#247]
possibly related to #242 

[this dataset](https://stirdata.opendata.cz/dataset?iri=https%3A%2F%2Fstirdata.opendata.cz%2Fresource%2Fdataset%2Fczechia%2Fares-res) shows that distribution license is unspecified. It is, however, specified in the data (via dcterms:license).

**Comment by skodapetr** [comment]
In the given example, the license is set as a literal, as of now we expect the license to be a URL.
