### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#25]
Add a footer, similar to the one at https://data.gov.cz.opendata.cz and include a link to the data dump (https://nkod.opendata.cz/soubor/nkod.trig.gz) and to the SPARQL endpoint (https://nkod.opendata.cz/sparql).

**Comment by skodapetr** [comment]
See https://github.com/linkedpipes/dcat-ap-viewer/wiki/Customization
