### ISSUE TITLE
URL query

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/dcat-ap-viewer#250]
Should we support both of them?
 * https://data.gov.cz/datové-sady?klíčová%20slova=celkový%20přírůstek
 * https://data.gov.cz/datové-sady?klíčová-slova=celkový%20přírůstek

**Comment by jakubklimek** [comment]
I think that a URL parameter name with a space in it, which needs to be always escaped, is weird. I would drop it.

**Comment by skodapetr** [comment]
Have we got that one before? As I saw it used on one place.

**Comment by skodapetr** [comment]
Add support for the previously used query parameters.
