### ISSUE TITLE
On mobile, dataset detail opens on the bottom of the page

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#261]
On mobile, when I click on a dataset in the dataset list, the dataset detail opens scrolled to the bottom, or to the middle of the page instead of to the top.

**Comment by skodapetr** [comment]
I was unable to reproduce that can you please provide more details?

**Comment by jakubklimek** [comment]
https://user-images.githubusercontent.com/718827/118775322-18bbf900-b887-11eb-8aa8-d0b5f27a87e6.mp4
