### ISSUE TITLE
Support Formal Open Standards better

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#266]
Currently, the links to FOS look like any other specification:
![image](https://user-images.githubusercontent.com/718827/123592700-decb0480-d7ed-11eb-895b-3557b6d0acc1.png)

We should emphasize FOS more, something like:
![image](https://user-images.githubusercontent.com/718827/123593015-4a14d680-d7ee-11eb-8f81-fca283acfccb.png)

The question is how to approach this, i.e. where to put the IRI -> FOS labels (en, cs). Currently, there is no machine readable list anywhere, so it would have to be a part of DAV (couchdb?), manually updated. This is, however, doable, since there were no changes in FOSes in the last year, therefore the changes are not frequent. When they become frequent, we can replace this with a more automated approach.

**Comment by skodapetr** [comment]
We can employ the IRI labels, already stored in the CouchDB. The idea is that whenever loading specification we try to load the label, form the "labels" database, and if no label is provided we use the default "Zobrazit specifikaci".
