### ISSUE TITLE
Add "show 10 more item" option to lists

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/dcat-ap-viewer#35]

**Comment by jakubklimek** [comment]
Is this really necessary at this moment?

**Comment by skodapetr** [comment]
It is more nice to have.
As for example there can be 81 datasets and then user need to switch from page to page, which is annoying.

However it is true that there are questions that need to be answered prior to implementation of this issue.

**Comment by jakubklimek** [comment]
When I click on this here: https://dev.nkod.opendata.cz/datové-sady - I gen one more dataset in the list and thats it. Then it does not work anymore.

**Comment by skodapetr** [comment]
Any details on how to reproduce?

**Comment by jakubklimek** [comment]
Works now...
