### ISSUE TITLE
Add a "tag cloud" dataset index page

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#37]
Add a "tag cloud" dataset index page.

Tags are keywords, keyword size is number of datasets (for now).

**Comment by skodapetr** [comment]
See cfd90a8261ca3b20fcc21488a2e361ac1959ba05

**Comment by skodapetr** [comment]
Require database "static" in CochDB with document "keywords_by_publishers" of structure
```
{
"_id" : "keywords_by_publishers",
"json": [
{"value" : "{LABELS}", "count" : "{NUMBER OF OCCURRENCES}" }
]
}
```
