### ISSUE TITLE
Control characters in query

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/dcat-ap-viewer#50]
When a dataset label contains "-" and the dataset name is used in the query box, the dataset is not found. This is probably cause by handling of control characters.

**Comment by jakubklimek** [comment]
In https://nkod.opendata.cz:

- when you search for ``ISoSS``, autocomplete offers ``ISoSS číselník - Cizí jazyk``, and when selected, it works and finds the dataset.
- when you search for ``zaměs``, autocomplete offers ``Číselník ČSÚ: Klasifikace zaměstnání (CZ-ISCO) - úroveň 2 - Třída (kód 5706)``, and when selected, the dataset (https://nkod.opendata.cz/datová-sada?iri=https%3A%2F%2Fnkod.opendata.cz%2Fzdroj%2Fdatová-sada%2F224870456) is not found.
