### ISSUE TITLE
GoogleBot does not index dataset pages

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#52]
GoogleBot fetches and renders the index page, but does not follow links to dataset pages.

**Comment by skodapetr** [comment]
Add to header:
```<meta name=“robots“ content=“index, follow“>```
```<link rel=“canonical“ href=“https:/host/stranka1″ />```
Add to links to not follow (codelists, etc.. ):
```<a href="signin.php" rel="nofollow">sign in</a>```

**Comment by jakubklimek** [comment]
Added sitemaps. Should solve the problems.
