### ISSUE TITLE
Comma is omitted in search query

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#54]
See [this](https://nkod.opendata.cz/datov%C3%A9-sady?dotaz=Z%C3%A1kladn%C3%AD+v%C3%BDsledky+S%C4%8D%C3%ADt%C3%A1n%C3%AD+lidu%2C+dom%C5%AF+a+byt%C5%AF+2011&poskytovatel=%C4%8Cesk%C3%BD+statistick%C3%BD+%C3%BA%C5%99ad&po%C5%99ad%C3%AD=issued+desc).

Comma is lost in a query, so "Základní výsledky Sčítání lidu, domů a bytů 2011" is offered by autocomplete but returns nothing.

**Comment by skodapetr** [comment]
Is working for ```základní+výsledky+sčítání+lidu,``` or ```lidu,``` but not for ```*lidu,*```.

**Comment by skodapetr** [comment]
https://stackoverflow.com/questions/40822478/solr-how-to-do-a-fq-with-a-comma-in-the-value

In general, this depends on how should a user be able to formulate queries.
We need to form a set of queries and then design the query formation and test that.

**Comment by jakubklimek** [comment]
Now it works.
