### ISSUE TITLE
dcterms:identifier is treated as URL in DAV (forms a link)

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#55]
dcterms:identifier is [treated as URL in DAV](https://dev.nkod.opendata.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fnkod.opendata.cz%2Fzdroj%2Fdatov%C3%A1-sada%2F240781) (forms a link), but it is a [Literal](https://www.w3.org/TR/vocab-dcat/#Property:dataset_identifier).

![image](https://user-images.githubusercontent.com/718827/38694178-3de25178-3e89-11e8-939a-113d75332ab8.png)

**Comment by jakubklimek** [comment]
I would actually hide it for now.

**Comment by skodapetr** [comment]
The value is actually an IRI  this is why a link is used. Later a label is requested for this IRI, once the label is fetched it is used in href as a label. 

Would there be no label found for given IRI, the IRI would be displayed instead. So we need to decide:
1) Should IRI be shown as link or text?
2) Once label for IRI is fetched should it be used as a label for link, or should the link be changed to text?
3) For which predicates (dcterms:identifier) this conversion should happen? There are other that are used as labels.

**Comment by jakubklimek** [comment]
According to the specification, the value is Literal, not IRI. So, it should not form a link and it should not be dereferenced. This can not be generalized for other properties which have IRIs as values.

**Comment by jakubklimek** [comment]
The value is definitely not an IRI, e.g. here: https://data.gov.cz/zdroj/datov%C3%A1-sada/http---vdb.czso.cz-pll-eweb-package_show-id-200068

**Comment by skodapetr** [comment]
Ok it is just about one property then.
I though that this applies to accrualPeriodicity as well, as it is part of the screenshot.

**Comment by skodapetr** [comment]
This is no longer valid as we reworked the UI.
