### ISSUE TITLE
Make available filters configurable

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#56]
In some catalogs there may not be dates (issued, modified) at all and then it is confusing to have date sorting filters. Disabling/enabling them could be configurable.

**Comment by skodapetr** [comment]
Filters could be removed as in nkod branch. Should there be a requirement for finer customisation please reopen the issue. In such case however we should choose more general approach to customisation rather then implement this for these two properties only.
