### ISSUE TITLE
Reimplement distributions list as Bootstrap Cards

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#59]
I think the distributions list could look and feel better implemented as [Cards](https://getbootstrap.com/docs/4.1/components/card/) with no image.
Distro title ~ card title
Distro format title ~ card subtitle
Download ~ Link 1
License ~ Link 2
Schema ~ Link 3 (if available)

Pagination could stay similar to what it is now.

**Comment by skodapetr** [comment]
http://getbootstrap.com/docs/4.1/components/card/#titles-text-and-links

**Comment by skodapetr** [comment]
Already implemented
