### ISSUE TITLE
React warning on some datasets

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#65]
e.g. https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A1-sada%2Fhttp---opendata.praha.eu-api-3-action-package_show-id-adopce-zvirat

**Comment by skodapetr** [comment]
As of now there is no warning.
