### ISSUE TITLE
Keyword facet could be word-cloud based

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#68]
Use case: Open the catalog, click on a publisher facet, e.g. Český statistický úřad. A publisher-specific keyword word cloud would be displayed before the dataset listing. Click on the keyword here would add/remove it to/from a filter.

**Comment by skodapetr** [comment]
How should the tag cloud look like, where should it be located (between search box and listing)?

**Comment by jakubklimek** [comment]
Yes, that was the idea. Maybe the tag cloud could represent keywords from the currently filtered datasets in general. I realize this would mean playing around with Solr/CouchDB/Virtuoso, but it could provide an additional type of overview of the currently filtered datasets.

**Comment by skodapetr** [comment]
Add new views: themes tag clouds, keywords tag cloud as alternatives to dataset list.
Add a way to change them under the search box.
