### ISSUE TITLE
In Firefox after URL edit, URL stops updating

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#69]
In Firefox, when browsing in LP-DAV, the URL in the browser chagnes normally.
When I edit the URL in the browser URL bar (e.g. add space), the URL stops updating when I continue browsing.

**Comment by skodapetr** [comment]
And have you hit enter after the update? As it seems that firefox just keep the URL in user edited form. In Chrome that is not the case as chrome empty the URL after modification and then use the new one - as current is empty.

You can observe the same behaviour on LP-ETL demo.
