### ISSUE TITLE
Add search by EU theme, similarly to how it is now done with keywords

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#74]
They should have a facet above keywords, and a search parameter in search results URI.

**Comment by skodapetr** [comment]
Should this include all themes, or with exclusion of Dataset theme?

**Comment by jakubklimek** [comment]
All themes, I would say.

**Comment by jakubklimek** [comment]
In dataset detail, we will have to add 2 links to everything we can search for in the app. One is search in app, one is dereference (e.g. a link icon).

**Comment by jakubklimek** [comment]
https://material.io/tools/icons/?icon=open_in_new&style=baseline
