### ISSUE TITLE
"(Ne)obsahuje osobní údaje" will now be optional

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#89]
"(Ne)obsahuje osobní údaje" will have a third option "Může obsahovat osobní údaje (nespecifikováno)", for `https://data.gov.cz/podmínky-užití/není-specifikováno-zda-obsahuje-osobní-údaje/`

Related to https://github.com/linkedpipes/dcat-ap-forms-vue/issues/22

**Comment by skodapetr** [comment]
Do you have a reference to any dataset with that property?

**Comment by jakubklimek** [comment]
https://dev.nkod.opendata.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2Fhttps---data.cssz.cz-api-3-action-package_show-id-doba-rizeni-o-namitkach
